[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faiss-cpu>=1.11.0.post1",
    "google-generativeai>=0.8.5",
    "pypdf>=5.9.0",
    "python-dotenv>=1.1.1",
    "streamlit>=1.47.1",
]
